:toc:

# Semester-Tracker

## 1. Einführung:

Eine einfache Webanwendung, mit welcher der Fortschritt von Klausurzulassungen interaktiv mitverfolgt werden soll. Dabei können sich Studierende über Github anmelden
und persönliche Module hinzufügen. Mit jeder neuen Abgabe kann dann die bisher erreicht Punktzahl aktualisiert und im Bezug zu der Zulassungsgrenze beobachtet werden.

Dies soll mit Hilfe einer Spring Boot Webanwendung realisiert werden. Dies ist ein Projekt, welches sehr gerne von Studierenden genutzt werden kann, um auf der einen Seite das Verständnis von und dem Umgang mit Spring Boot fördern soll. 

Für bereits erfahrenere Studierende, oder Studierende welche gerne an der Entwicklung dieses Tools beteiligt sein möchten, soll dieses Projekt allerdings auch die Möglichkeit
bieten, Pull Requests zu stellen und tatsächlich effektiv an dem Projekt mitzuarbeiten!

## 2. Features:

- [ ] Strukturierte und intiutive Webansicht
- [ ] Hinzufügen von Modulen
- [ ] Aktualisierung der Punktzahl
- [ ] Übersicht aller Module
- [ ] Übersicht aller Punktzahlen
- [ ] Bearbeitung der Module
- [ ] Sicherung der Pfade mit Security
- [ ] Authentifizierung über GitHub (Eher SPAM-Schutz)
- [ ] Persistente Datenbank

## 3. Contribution:

Es dürfen gerne Pull-Requests gestellt werden. Dabei soll insgesamt auf den https://berlincodeofconduct.org/de/[Berlin Code of Conduct] geachtet werden.
Außerdem ist es unerlässlich gängige Java Konventionen und Clean Code Prinzipien einzuhalten, da dies den Aufwand der Code Reviews für die einzelnen Pull Requests 
erheblich reduziert.

## 4. Dependencies:

Die in dem folgenden Screenshot angezeigten Dependencies werden genutzt:



## 5. Lizenz:

Informationen zu den Nutzungsbedingungen können https://github.com/MarcoSteinke/Semester-Tracker/blob/main/LICENSE[hier] entnommen werden.
